### ISSUE TITLE
Error when getting recently created asset

### ISSUE THREAD

**Issue by hazelmeow** [Sleitnick/rbxcloud#34]
```rust
ReqwestError(
  reqwest::Error {
    kind: Decode,
    source: Error("missing field `done`", line: 1, column: 61),
  },
),
```
If I add a few seconds sleep after creating the asset it'll work and have `done: true` but it'd be nice to get proper responses with `done: false`

**Comment by notme1560** [comment]
There's an open PR already oops #32
