### ISSUE TITLE
I cannot publish rbxl in Start Place

### ISSUE THREAD

**Issue by FelipeMartinsFrudeli** [Sleitnick/rbxcloud#37]
I can only publish in created places of Universe, but I can't publish in Start Place

![image](https://github.com/Sleitnick/rbxcloud/assets/51006430/cb4f0752-7ea8-4cb4-9f18-3fc3ee3f7482)

I followed the "Advanced Roblox Project Setup" tutorial, and I was able to publish normally in Staging, but in Production I had some problems only with Start Place. (I have checked IDs multiple times, and created other places)

Enabled permissions:
- Enable Studio access to API services
- Allow place to be copied as a template using Create Place API
- Allow place to be updated using Save Place API

API Key Permission:
- Place Publishing, Write

Version:
- rbxcloud 0.6.0
- foreman 1.5.0

**Comment by FelipeMartinsFrudeli** [comment]
I turned off "Team Create" and it worked normally. Why did this happen?

**Comment by FelipeMartinsFrudeli** [comment]
You are right, it only works when the studio is closed. Thanks for the helping.

**Comment by Sleitnick** [comment]
No problem @FelipeMartinsFrudeli, glad it's solved! FWIW, this message is hard-coded into `rbxcloud` for `409` HTTP errors; however, the text was grabbed from the documentation [here](https://create.roblox.com/docs/reference/cloud/universes-api/v1). I wonder if I can put in a PR to the docs to get that changed.

**Comment by Sleitnick** [comment]
I've opened up #38 to investigate and clarify this message.
