### ISSUE TITLE
EOF Parsing Error when trying to list-stores

### ISSUE THREAD

**Issue by Zenthial** [Sleitnick/rbxcloud#5]
I ran `rbxcloud datastore list-stores --universe-id myUniverseId --api-key myAPIKey --limit 10`, and was given this error message
![image](https://user-images.githubusercontent.com/26680614/181921158-d7982b60-034c-42b2-9bf7-84803c3e889a.png)

**Comment by Sleitnick** [comment]
This was caused by a leading `/` in the URL for listing DataStores
